import { Container, Typography, Box, Paper } from '@mui/material'

export default function TermsPage() {
  return (
    <Box sx={{ bgcolor: 'background.default', minHeight: '100vh', py: 6 }}>
      <Container maxWidth="md">
        <Typography variant="h3" component="h1" gutterBottom fontWeight={700}>
          Terms of Service
        </Typography>
        <Typography variant="body2" color="text.secondary" paragraph>
          Last updated: November 2025
        </Typography>

        <Paper variant="outlined" sx={{ p: 4, mt: 4 }}>
          <Typography variant="h5" gutterBottom fontWeight={600}>
            Acceptance of Terms
          </Typography>
          <Typography paragraph>
            By accessing and using Crow Create, you accept and agree to be bound by these Terms of
            Service. If you do not agree to these terms, please do not use this service.
          </Typography>

          <Typography variant="h5" gutterBottom fontWeight={600} sx={{ mt: 4 }}>
            Description of Service
          </Typography>
          <Typography paragraph>
            Crow Create is a free, browser-based design system helper tool that allows you to
            create color palettes, configure typography, and generate exportable design tokens. The
            service operates entirely client-side in your web browser.
          </Typography>

          <Typography variant="h5" gutterBottom fontWeight={600} sx={{ mt: 4 }}>
            No Warranty
          </Typography>
          <Typography paragraph>
            Crow Create is provided "as is" without warranty of any kind, either express or
            implied, including but not limited to warranties of merchantability, fitness for a
            particular purpose, or non-infringement.
          </Typography>
          <Typography paragraph>
            We do not warrant that the service will be uninterrupted, error-free, or free of
            viruses or other harmful components.
          </Typography>

          <Typography variant="h5" gutterBottom fontWeight={600} sx={{ mt: 4 }}>
            Limitation of Liability
          </Typography>
          <Typography paragraph>
            In no event shall Crow Create or its operators be liable for any indirect, incidental,
            special, consequential, or punitive damages arising out of or related to your use of
            the service.
          </Typography>

          <Typography variant="h5" gutterBottom fontWeight={600} sx={{ mt: 4 }}>
            User Responsibilities
          </Typography>
          <Typography paragraph>
            You are responsible for:
          </Typography>
          <Box component="ul" sx={{ pl: 3 }}>
            <li>Ensuring that any code or configurations generated by Crow Create are appropriate for your use case</li>
            <li>Testing generated code before deploying to production</li>
            <li>Ensuring compliance with applicable accessibility standards and regulations</li>
            <li>Backing up any design projects you create (we recommend exporting or saving locally)</li>
          </Box>

          <Typography variant="h5" gutterBottom fontWeight={600} sx={{ mt: 4 }}>
            Intellectual Property
          </Typography>
          <Typography paragraph>
            You retain all rights to design systems and configurations you create using Crow
            Create. The Crow Create application itself and its source code are protected by
            copyright and other intellectual property laws.
          </Typography>

          <Typography variant="h5" gutterBottom fontWeight={600} sx={{ mt: 4 }}>
            Acceptable Use
          </Typography>
          <Typography paragraph>
            You agree not to use Crow Create for any unlawful purpose or in any way that could
            damage, disable, overburden, or impair the service.
          </Typography>

          <Typography variant="h5" gutterBottom fontWeight={600} sx={{ mt: 4 }}>
            Modifications to Service
          </Typography>
          <Typography paragraph>
            We reserve the right to modify, suspend, or discontinue Crow Create at any time without
            notice. We shall not be liable to you or any third party for any modification,
            suspension, or discontinuance of the service.
          </Typography>

          <Typography variant="h5" gutterBottom fontWeight={600} sx={{ mt: 4 }}>
            Changes to Terms
          </Typography>
          <Typography paragraph>
            We may revise these Terms of Service at any time. Continued use of Crow Create after
            changes are posted constitutes acceptance of the revised terms.
          </Typography>

          <Typography variant="h5" gutterBottom fontWeight={600} sx={{ mt: 4 }}>
            Governing Law
          </Typography>
          <Typography paragraph>
            These terms shall be governed by and construed in accordance with applicable laws,
            without regard to conflict of law provisions.
          </Typography>
        </Paper>
      </Container>
    </Box>
  )
}
